name: update tag

on:
  push:
    branches:
      - master
      - main
      - workflows
    
jobs:
  push_to_registry:
    name: Build & upload to GitHub registry
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: package-version
      run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
    
    - uses: rickstaa/action-create-tag@v1.6.1
      id: "tag_create"
      with:
        tag: v${{ env.PACKAGE_VERSION }}
        tag_exists_error: false
        message: "version v${{ env.PACKAGE_VERSION }}"
    
    -  run: |
        echo "Tag already present: ${{ env.TAG_EXISTS }}"